### ISSUE TITLE
Using the latest version of the library in `time` repository leads to an exception

### ISSUE THREAD

**Issue by yevhenii-nadtochii** [SpineEventEngine/mc-java#29]
Using of the latest version of `spine-mc-java` in `time` repository fails the build with an exception. 

The problematic version is `2.0.0-SNAPSHOT.90`.

```
Exception in thread "main" java.lang.IllegalStateException: Unexpected time: `TIME_UNDEFINED`.
        at io.spine.validation.java.InTimeGeneratorKt.formatJavaComparison(InTimeGenerator.kt:84)
        at io.spine.validation.java.InTimeGeneratorKt.access$formatJavaComparison(InTimeGenerator.kt:1)
        at io.spine.validation.java.TimestampInTimeGenerator.condition(InTimeGenerator.kt:72)
        at io.spine.validation.java.CodeGenerator.code(CodeGenerator.kt:66)
        at io.spine.validation.java.SimpleRuleGenerator.code(SimpleRuleGenerator.kt:85)
        at io.spine.validation.java.JavaValidationRenderer.generateValidationCode(JavaValidationRenderer.java:222)
        at io.spine.validation.java.JavaValidationRenderer.generateCode(JavaValidationRenderer.java:141)
        at io.spine.validation.java.JavaValidationRenderer.lambda$render$3(JavaValidationRenderer.java:128)
        at ...

> Task :time:launchProtoDataTest FAILED
```

**Comment by armiol** [comment]
Already addressed.
