### ISSUE TITLE
`java.lang.NoSuchMethodError` at `HandleMethodResult.java:58` when using ErrorProne after v 2.10.0

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/mc-java#42]
An attempt to use ErrorProne with the version after 2.10.0 results in an error with the following cause:

```
Caused by: java.lang.NoSuchMethodError: com.google.errorprone.bugpatterns.CheckReturnValue: method 'void <init>()' not found
        at io.spine.tools.mc.java.checks.check.methodresult.HandleMethodResult.<init>(HandleMethodResult.java:58)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
        ... 176 more
```

This was discovered in the `core-java` project, when attempting to bump ErrorProne to anything younger. But this issue probably prevents us from using newer ErrorProne in other projects too.

This happens before in ErrorProne v.2.11.0 a parameterless constructor (which we use) was removed.

**Comment by alexander-yevsyukov** [comment]
@armiol, this is the issue I've just created. If it duplicates already existing, please point me to it, and I'll update the code comments referencing this matter from `core-java`.

**Comment by armiol** [comment]
See [time#139](https://github.com/SpineEventEngine/time/issues/139) and [core-java#1446](https://github.com/SpineEventEngine/core-java/issues/1446).

**Comment by armiol** [comment]
Addressed already.
